Dev
HappyKod/service-api-gofermart pull request #1
Opened 2022-11-13 18:37 UTC by HappyKod

2022-11-22 21:17 UTC, tmvrus requested changes
не выполнено условие задания
```
хранилище данных — PostgreSQL;
```

2022-11-23 05:49 UTC, HappyKod commented
> не выполнено условие задания
> 
> ```
> хранилище данных — PostgreSQL;
> ```

Хай)
Вроде как это промежуточное ревью проекта.
В остально все норм?

P.S. Я это указал в README.md

2022-11-23 16:13 UTC, tmvrus requested changes
Есть недочеты.

2022-11-23 16:13 UTC, tmvrus commented on internal/app/service/calculation-loyalty-points.go
> +				loyaltyPoint.Status = "PROCESSING"
есть константы для этих статусов же

2022-11-23 16:13 UTC, tmvrus commented on internal/storage/storage.go
> +	GetManyWithdraws(userLogin string) ([]models.Withdraw, error)
Ни в одном методе нет передачи внешнего контекста, рекомендую все же начать это делать, что бы код перестал выглядеть студенческим.

2022-11-23 16:13 UTC, tmvrus commented on internal/app/service/calculation-loyalty-points.go
> +func CalculationLoyaltyPoints() error {
в эту ф-ю лучше тоже побрасывать внешний контекст, и передавать его в http-запросы и storage-layer

2022-11-23 16:13 UTC, tmvrus commented on internal/storage/pgstorage/pg-storage.go
> +	sliceStatus := []interface{}{constans.OrderStatusPROCESSING, constans.OrderStatusNEW, constans.OrderStatusREGISTERED}
PROCESSED тут лишний, это заказ для которого уже получены начисления

2022-11-23 16:13 UTC, tmvrus commented on internal/app/handlers/login-handler.go
> +		return
415 Unsupported Media Type?
во всех местах где проверяется

2022-11-23 16:13 UTC, tmvrus commented on internal/app/service/calculation-loyalty-points.go
> +
тут зачем-то перевод строки

2022-11-23 16:13 UTC, tmvrus commented on internal/constans/constants.go
> +	TimeSleepTooManyRequests          = 60
если сразу сделать константу типизированной
TimeSleepTooManyRequests = time.Second * 60
то в дальнейшем ее не придется умножать

2022-11-23 16:13 UTC, tmvrus commented on internal/constans/constants.go
> +	TimeSleepCalculationLoyaltyPoints = 1
эту константу тоже вполне можно сделать типизированной

2022-11-23 16:13 UTC, tmvrus commented on internal/app/handlers/add-withdraw-handler.go
> +	current := sum - spent
между получением баланса и списанием средств может быть другой запрос на списание, это нарушит консистентность данных

2022-11-29 10:57 UTC, tmvrus approved these changes
Получилось хорошо, есть только косметические недочеты

2022-11-29 10:57 UTC, tmvrus commented on internal/app/handlers/register-handler.go
> +	//<-ctx.Done()
лишний коментарий

2022-11-29 10:57 UTC, tmvrus commented on internal/app/handlers/register-handler.go
> +	fmt.Println(errors.Is(ctx.Err(), context.Canceled))
вывод отладочной информации

2022-11-29 10:57 UTC, tmvrus commented on internal/app/server/server.go
> +	}
Fatal в этой ф-и завершит все приложение и defer в main не отработает

2022-11-29 10:57 UTC, tmvrus commented on internal/app/service/calculation-loyalty-points.go
> +		cancel()
субъективно, этот цикл выглядит перегруженным, как минимум из-за обилия cancel после проверки на ошибку, если убрать код взаимодействия с системой начисления в отдельную ф-ю, то там можно будет проверять это только один раз в defer

2022-11-29 10:57 UTC, tmvrus commented on internal/storage/pgstorage/pg-storage.go
> +		 status_order varchar(50),
статусов заказов у нас ограниченное количество, для таких кейсов в postgresql есть enum type, рекомендую ознакомиться

2022-11-29 10:57 UTC, tmvrus commented on internal/storage/pgstorage/pg-storage.go
> +	);
тут нет явного primary key, но можно использовать number_order

2022-11-29 10:57 UTC, tmvrus commented on internal/storage/pgstorage/pg-storage.go
> +	from public.orders where status_order in ($1, $2, $3)`, sliceStatus...)
это придется править каждый раз когда будет меняться число статусов/аргументов, есть хорошая альтернатива status_order IN ($1) или status_order ANY ($1) и можно передавать массив в качестве аргумента

2022-11-29 10:57 UTC, tmvrus commented on internal/storage/pgstorage/pg-storage.go
> +	`, withdraw.UserLogin, withdraw.NumberOrder, withdraw.Sum, withdraw.ProcessedAT)
в этих запросах не помешало бы форматирование

2022-11-30 07:16 UTC, merged